### ISSUE TITLE
mkdocsoad 0.1.2 breaks with empty component schemas

### ISSUE THREAD

**Issue by mikegb** [Neoteroi/mkdocs-plugins#23]
Hey there, love the plugin for generating OpenAPI docs pages with mkdocs. I was implementing it with one of our openapi schemas and ran into an issue.

Namely generating a docs page for a schema like either of the following will fail with parsing errors, evidently because the `properties` attribute in the schema is empty.
```
openapi: 3.0.1
paths:
components:
  ...
  schemas:
    ...
    EmptyObject:
      type: object
    BrowserEventContext:
      type: object
      additionalProperties: true
```

I believe this is still valid OpenAPI syntax and may be a parsing error within the library. If you search https://swagger.io/specification/ for "additionalProperties" you can see examples of a similar valid specification.

Here's the relevant stack trace:

> ERROR    -  Error reading page 'webauthnapi/api.md': 'NoneType' object is not iterable
> Traceback (most recent call last):
>   File "/Users/mikegb/.pyenv/versions/3.10.8/bin/mkdocs", line 8, in <module>
>     sys.exit(cli())
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/click/core.py", line 1053, in main
>     rv = self.invoke(ctx)
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/click/core.py", line 754, in invoke
>     return __callback(*args, **kwargs)
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/mkdocs/__main__.py", line 234, in serve_command
>     serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 82, in serve
>     builder(config)
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 75, in builder
>     build(config, live_server=live_server, dirty=dirty)
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/mkdocs/commands/build.py", line 308, in build
>     _populate_page(file.page, config, files, dirty)
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/mkdocs/commands/build.py", line 177, in _populate_page
>     page.markdown = config.plugins.run_event(
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/mkdocs/plugins.py", line 514, in run_event
>     result = method(item, **kwargs)
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/neoteroi/mkdocsoad/__init__.py", line 44, in on_page_markdown
>     return self.rx.sub(self._replacer, markdown)
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/neoteroi/mkdocsoad/__init__.py", line 34, in _replacer
>     return handler.write()
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/openapidocs/mk/v3/__init__.py", line 417, in write
>     return self._writer.write(
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/openapidocs/mk/jinja.py", line 107, in write
>     return template.render(data, **kwargs)
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
>     self.environment.handle_exception()
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception
>     raise rewrite_traceback_stack(source=source)
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/openapidocs/mk/v3/views_markdown/layout.html", line 19, in top-level template code
>     {% include "partial/components-schemas.html" %}
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/openapidocs/mk/v3/views_markdown/partial/components-schemas.html", line 5, in top-level template code
>     {% include "partial/type.html" %}
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/openapidocs/mk/v3/views_markdown/partial/type.html", line 4, in top-level template code
>     {%- for name, schema in handler.get_properties(definition) %}
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/openapidocs/mk/v3/__init__.py", line 596, in get_properties
>     return [[key, value] for key, value in sort_dict(schema.get("properties"))]
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/openapidocs/mk/v3/__init__.py", line 596, in <listcomp>
>     return [[key, value] for key, value in sort_dict(schema.get("properties"))]
>   File "/Users/mikegb/.pyenv/versions/3.10.8/lib/python3.10/site-packages/openapidocs/mk/__init__.py", line 49, in sort_dict
>     for key in sorted(obj, key=str.lower):

**Comment by RobertoPrevato** [comment]
Hi @mikegb 
Thanks for reporting this bug. I'll fix this. If you could please share an example of your OpenAPI specification file, I'll ensure that it doesn't break in other ways, after this particular one is corrected.

**Comment by RobertoPrevato** [comment]
Hi @mikegb,
The bug you reported has been fixed in `essentials-openapi`. Please upgrade this dependency this way:

```
pip install -U essentials-openapi
```

It should download version `1.0.4`. It also includes [another bug fix](https://github.com/Neoteroi/essentials-openapi/issues/19).

**Comment by mikegb** [comment]
This worked great, thanks so much for the quick turn around! 

I did verify the docs site worked on our spec and that it was just the two schemas I mentioned that were failing. Unfortunately I think I'd probably break some company rules to share the internal spec, but thank you again!
