### ISSUE TITLE
Cannot seem to get timeline to function

### ISSUE THREAD

**Issue by sseekamp0** [Neoteroi/mkdocs-plugins#34]
Hello,
I'm trying to get a timeline added to my mkdocs-material site, but can't seem to quite understand how this package installs/works. 

1. I've run `pip3 install neoteroi-mkdocs` and that installed correctly.
2. I added the following to my mkdocs.yml that's at the root of my site
```
markdown_extensions:
  - neoteroi.timeline
 ```
and
```
extra_css:
  - css/neoteroi-mkdocs.css
```

However, I consistently get `WARNING  -  [12:39:06] "GET /docs/css/neoteroi-mkdocs.css HTTP/1.1" code 404` in my console output.

Questions:
1. I did notice in the introduction page of the documentation site you indicated that we had to download the CSS? Is that required or serve up timeline? or is it downloaded with the pip install? 
2. Can I copy the CSS output instead of downloading a file?
3. Do you have an example site of serving up the timeline? Couldn't find your mkdocs example site in this repo.

**Comment by RobertoPrevato** [comment]
Hi @sseekamp0 
Yes, it's necessary to download the CSS file and include it in your site folder. Distributing it with pip wouldn't work because it would get placed into your Python virtual environment, or Python global installation folder (depending on whether you use virtual environments or not). The MkDocs development server does not serve files in your dependencies folder.

> Couldn't find your mkdocs example site in this repo.

The documentation site is linked in the README of this repo, there are 8 links at the very top:

![image](https://user-images.githubusercontent.com/2576032/218591773-a838bbc5-36ec-43ea-8eb8-42588e4f33cf.png)

**Comment by scydas** [comment]
![image](https://user-images.githubusercontent.com/22952515/220082910-b632d5c5-f95d-46e9-ade8-daec1c4e918a.png)
I have the same problem.
Is the css file described in the documentation the file I marked up?

**Comment by RobertoPrevato** [comment]
Hi @scydas 
Yes, as described here https://www.neoteroi.dev/mkdocs-plugins/intro/#how-to-obtain-css-files

You can download the CSS from the assets of the last successful release, or from the published artifacts of the last successful GitHub Workflows run in GitHub.

From the release:

![image](https://user-images.githubusercontent.com/2576032/220085305-0b9eb5f8-759c-47b7-a5ec-497e85a1b0e6.png)

From the last action:

![image](https://user-images.githubusercontent.com/2576032/220085493-dd76efaf-7672-44d5-b7a8-34fffb261b1d.png)

In the first case, rename the CSS file as desired. In the second case, the file has already name "neoteroi-mkdocs.css", in only need to be unzipped.

**Comment by scydas** [comment]
@RobertoPrevato 
Thank you very much for your reply, I have a question.
 oad only supports swagger V3? not V2

**Comment by RobertoPrevato** [comment]
> @RobertoPrevato Thank you very much for your reply, I have a question. oad only supports swagger V3? not V2

You're welcome 😄. Yes, my libraries to handle OpenAPI Specification only support V3. Because I wouldn't have the time to support _also_ version 2. However, I generally structure my code to support adding support for V2 eventually in the future (or V4, when it will exist).
