### ISSUE TITLE
Not really an issue: I can't get cards running

### ISSUE THREAD

**Issue by quizilkend** [Neoteroi/mkdocs-plugins#48]
Hey there,

I am a bit ashamed to use the ticket system with my my question - if this is inappropriate please close the issue.

I would love to use the cards plugin for my index page.

What I did so far:
- added ```pip install neoteroi-mkdocs``` to the before script section in the CI
- downloaded the css-file from the latest release and put it under ```docs/css/neoteroi-mkdocs.css```
  - https://github.com/Neoteroi/mkdocs-plugins/releases/download/v1.0.4/css-v1.0.4.css
- added this to ```mkdocs.yml```
    ```
    extra_css:
    - css/neoteroi-mkdocs.css
    markdown_extensions:
    - neoteroi.cards
   ```
- Added som example code to an existing ```*.md```-file.
```
::cards:: cols=2

- title: Zeus
  content: Lorem ipsum dolor sit amet.

- title: Athena
  content: Lorem ipsum dolor sit amet.

- title: Poseidon
  content: Lorem ipsum dolor sit amet.

- title: Artemis
  content: Lorem ipsum dolor sit amet.

- title: Ares
  content: Lorem ipsum dolor sit amet.

- title: Nike
  content: Lorem ipsum dolor sit amet.

::/cards::
```

I see the text on the corresponding page, but not in cards.
Can you point me to what I am doing wrong?

Thank you very much!
Samuel

**Comment by quizilkend** [comment]
Oh sorry.
Actually it seemed to be a caching issue. Now it's working - sorry that I bothered.

**Comment by RobertoPrevato** [comment]
Hi Samuel,
No reason to feel ashamed of asking a question. I'm glad it was just caching. :)
Thank You for leaving a message.
