### ISSUE TITLE
Is not a bug, but i can't found the neoteroi.mkdocs.css file

### ISSUE THREAD

**Issue by filipeaecio** [Neoteroi/mkdocs-plugins#52]
Hello,

I'm trying to follow the steps provided in the documentation to use OpenAPI Docs, but I couldn't find the neoteroi.mkdocs.css file.

Tks

**Comment by RobertoPrevato** [comment]
Hi @filipeaecio 
The releases in GitHub include a CSS asset
https://github.com/Neoteroi/mkdocs-plugins/releases/tag/v1.0.4
