### ISSUE TITLE
🙋 Pick the color of the item icon in timeline

### ISSUE THREAD

**Issue by yodamad** [Neoteroi/mkdocs-plugins#61]
Hi

I was trying to set the background color of my icon in the timeline plugin.
I thought it was through the `key` attribute, but I didn't manage to do so.

The sample `key: pink` in the documentation doesn't work :(

Is it possible ? If so, how ?

Thank you for the help :)

**Comment by RobertoPrevato** [comment]
Hi @yodamad 
I verified the `key` property works as documented: it applies CSS classes to elements, which enables styling.

Consider this example, to set the background color of icons in a timeline:

- adding a `key` property to specify a CSS class for the HTML elements

```
::timeline:: class="epic-timeline"
- title: Zeus does something
  content: ...
  icon: ./img/icons/001-zeus.png
  sub_title: Turn 1
  key: zeus
::/timeline::
```

Then you would include a CSS rule in your custom style sheet for MkDocs to override the background color of dots, for example:

```css
.nt-timeline-dot.zeus.bigger {
  background: gold;
  border-color: gold;
}
```

![image](https://github.com/user-attachments/assets/5ec3bf5d-b2c8-48f9-94e0-08f1a6de8a20)

Both the `.nt-timeline-item` and the `.nt-timeline-dot` elements include the configured class.

**Comment by yodamad** [comment]
👍 Thank you it works
Misread the documentation
